{% set name = "datarobot" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f89dddf377df7d0f9c059c8cd944db996b4990d195c10c59f8e5a19855b80d76

build:
  # typing-extensions 4.3.0 not available for python 3.11
  skip: true  # [py<3.7 or py==311]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pandas >=0.15
    - pyyaml >=3.11
    - requests >=2.21
    - requests-toolbelt >=0.6
    - trafaret >=0.7,<2.2,!=1.1.0
    - urllib3 >=1.23
    - contextlib2 >=0.5.5
    - typing-extensions 4.3.0
    - numpy

test:
  requires:
    - pip
  imports:
    - datarobot
  commands:
    - pip check

about:
  home: https://www.datarobot.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: This client library is designed to support the DataRobot API.
  description: |
    datarobot is a client library for working with the <https://www.datarobot.com/> platform API.
  doc_url: https://datarobot-public-api-client.readthedocs-hosted.com
  dev_url: https://github.com/datarobot

extra:
  recipe-maintainers:
    - dsakagi
    - alexalokhinrobot
    - axik
    - mbromanowsky
    - AndrewSonwat
    - lperri
    - ahjota
