travis:
  secure:
    BINSTAR_TOKEN: KzXC2HIGqUtXnULTXcClY6eA2hxk5iPoWMgeklOFwEP0MqtYeLOvgUnx8VTDCj5oVKpNGk8deYi85fYFb7Re+Ktengg6Zth+G0V0rezqWfNCU/zOHrrLVH1XFlBGlM/Q07bKhphGCjWoo6Rwzjp0LEbxKeDbiQ3NSEJuZC73pgOqjilisz45zgIdSqkLkzF0nWJRb7llNIT1car4p/msuHI2LMLM86t7q3kzKbTa8dB4sgGkwZ+bT6G/AustHjI6xT18ADTKsjOoWxUFQ45HlSPQF7qJ+Yb7V2F3x3gcEAaFZdO/GWgsdV9kxcVq4hjX/F/UQsjjMytXF/fak+NV9NbRT8OKaa167LJqHSVzwcS0t1kzx6NiV/GfNCiIl1lj75GOtos9A2xWAWjwKUoi0xXYL4vJ0YkgRqSUBFn7yY6jO3FDkt8J1CJPNp7dAzppQq8I7rMr3CxLrISdyDD7YfYRxl6tMrxv8Io4B6b4ezNUpe7DTJFim4kZEpuJ+vtO3oa6yGYuLxYIsogxZvGzcbSU0+ssvtWlRC9vP0dkrbSCLdQBZ8grYwPf2n5AjA2Tp0EtTfth5sXqmZ8uLfK7ADptYY7RygDlifutunKh8KoUTE37OREr1n+gLYPcKeCZCewBWdb8fmaGfFDWH3pJt1wepkDdR94lJYTfOSs87FQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
