travis:
  secure:
    BINSTAR_TOKEN: p5+21NzE9qCtcXokHGiwLH7zIH1kL7lpiBj3jANTeDNw+GRCpkh2H9Z6V2NmoKc5boiofieYRGqw32vOlKpW7up6GBU1twV9NmWPyiuGuGJ1dMntdBmvyJ3QjTtk3Iz7xzaNi0ZFcZGZQidUa6LRIqxpTZKI8YvwdU9AkI7HQKWqP6Gbehkn3b0J62rpMrNuXsLjuJGXjC87273+NOWH8NdoE7i7VTSJWn8sa/7zKBd9Ve9V4v+ZoHnLBT3v3oHpN3ccxzmhjzKFCRp1UAfBid/nwBDhANbLZVr6uk8p2HGD7mQJCCRaIPOyNh1xOyMl1BChA6Gl9ytGxDZY8oIhiCx5gIFSCGNufQnh+QDpOAJbd9WW3PwFSD979lzV6ITJ7JDblYbv1RUS7DfnSDy/bntDYtRKMz4nfNVA8z6zUoVAcX6+acYvqA2l3uUbxugSkehJ0iGnXLkIszTQZKs362RSnlr4mbpt0bI84MbwMmMYdafhzNBjwT0yjeWDn/0I+680/CiIGSxtAyHWpHW+NVhz8R/q34oiqP+CldV2VtN3VStRgH8JdP0dTAn2sqQY1osPj8Zd5UHrkY5CASFdeOmC2ORvBrqgVYb6Is/PeUU03KzkvGkI9266KxDyyMx4JtPA1hwXvViFr7+sZipK11A75w3Q/sW89Z8HroJfjqE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
